/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grades
         * @description Table 5.1.
         */
        get: operations["grades_api_v1_grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Symbols
         * @description The symbol glossary: one line per symbol. `topic` is material, deformation or tension.
         */
        get: operations["symbols_api_v1_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/csm-coefficients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csm Coefficients
         * @description Table B.1.
         */
        get: operations["csm_coefficients_api_v1_csm_coefficients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/material-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Material Model
         * @description B.4: the CSM bilinear model for a material.
         */
        post: operations["material_model_api_v1_material_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tension
         * @description B.6.1: CSM tension resistance.
         */
        post: operations["tension_api_v1_tension_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deformation-capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deformation Capacity
         * @description B.5: cross-section slenderness and the strain limit eps_csm / eps_y (B.6, B.7).
         */
        post: operations["deformation_capacity_api_v1_deformation_capacity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/section-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Section Comparison
         * @description B.5 for the same section made thicker and thinner, to compare stocky with slender.
         */
        post: operations["section_comparison_api_v1_section_comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CapSourceKey
         * @enum {string}
         */
        CapSourceKey: "omega" | "material_ductility";
        /** CoefficientsOut */
        CoefficientsOut: {
            family: components["schemas"]["StainlessFamily"];
            /** C1 */
            c1: number;
            /** C2 */
            c2: number;
            /** C3 */
            c3: number;
            /**
             * Selected
             * @default false
             */
            selected?: boolean;
        };
        /** ComparisonPointOut */
        ComparisonPointOut: {
            /**
             * Factor
             * @description Every thickness is multiplied by this
             */
            factor: number;
            /** Slenderness */
            slenderness: number;
            zone: components["schemas"]["ZoneKey"];
            /** Strain Ratio */
            strain_ratio: number | null;
            /** Strain */
            strain: number | null;
            /**
             * Stress
             * @description Stress read from the B.4 curve at the strain [N/mm2]
             */
            stress: number | null;
        };
        /**
         * ComparisonRequest
         * @description Same inputs as B.5. The section must be plates or a circular hollow section.
         */
        ComparisonRequest: {
            material: components["schemas"]["MaterialInput"];
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input
             */
            poisson_ratio?: number | null;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            values: components["schemas"]["ModelValuesOut"];
            /** Switch */
            switch: number;
            /** Upper */
            upper: number;
            /** Cap */
            cap: number;
            /** Points */
            points: components["schemas"]["ComparisonPointOut"][];
            /** References */
            references: components["schemas"]["ReferenceSectionOut"][];
            /** Base Curve Figure */
            base_curve_figure: {
                [key: string]: unknown;
            };
            /** Stress Figure */
            stress_figure: {
                [key: string]: unknown;
            };
            /** Notes */
            notes: string[];
        };
        /** DeformationRequest */
        DeformationRequest: {
            material: components["schemas"]["MaterialInput"];
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input; not needed with sigma_cr
             */
            poisson_ratio?: number | null;
        };
        /** DeformationResponse */
        DeformationResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            slenderness: components["schemas"]["SlendernessOut"];
            strain_limit: components["schemas"]["StrainLimitOut"];
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /** Figure */
            figure: {
                [key: string]: unknown;
            };
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error Type */
            error_type: string;
        };
        /**
         * FamilyKey
         * @enum {string}
         */
        FamilyKey: "flat_plates" | "circular_hollow";
        /**
         * GeometryInput
         * @description The section. Which fields are needed depends on `kind` (the API says what is missing).
         */
        GeometryInput: {
            kind: components["schemas"]["GeometryKindKey"];
            /**
             * D
             * @description Outer diameter [mm] (CHS)
             */
            d?: number | null;
            /**
             * T
             * @description Wall thickness [mm] (CHS)
             */
            t?: number | null;
            /** Plates */
            plates?: components["schemas"]["PlateInput"][];
            /**
             * Sigma Cr Cs
             * @description sigma_cr,cs [N/mm2]
             */
            sigma_cr_cs?: number | null;
            /** @description With sigma_cr only */
            family?: components["schemas"]["FamilyKey"] | null;
        };
        /**
         * GeometryKindKey
         * @enum {string}
         */
        GeometryKindKey: "chs" | "plates" | "sigma_cr";
        /**
         * GoverningKey
         * @description Which term of Formula B.14 governs the tensile strain limit (stable machine key).
         * @enum {string}
         */
        GoverningKey: "fixed_limit_15" | "material_ductility";
        /** GradeOut */
        GradeOut: {
            /** Designation */
            designation: string;
            /** Label */
            label: string;
            family: components["schemas"]["StainlessFamily"];
            /** Strength Class */
            strength_class: string | null;
            /** Corrosion Class */
            corrosion_class: string | null;
            /** Fy */
            fy: number;
            /** Fu */
            fu: number;
            /** Note */
            note: string | null;
        };
        /**
         * GraphView
         * @enum {string}
         */
        GraphView: "schematic" | "true_scale";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MaterialInput
         * @description A Table 5.1 grade (give `designation`) or a custom material (leave it out).
         */
        MaterialInput: {
            /**
             * Designation
             * @example 1.4307
             */
            designation?: string | null;
            family?: components["schemas"]["StainlessFamily"] | null;
            /**
             * Fy
             * @description Yield strength [N/mm2], custom only
             */
            fy?: number | null;
            /**
             * Fu
             * @description Ultimate strength [N/mm2], custom only
             */
            fu?: number | null;
            /**
             * Elastic Modulus
             * @description E [N/mm2], an input
             */
            elastic_modulus: number;
            /**
             * Enhanced
             * @description Custom values enhanced by cold-forming
             * @default false
             */
            enhanced?: boolean;
        };
        /** MaterialModelRequest */
        MaterialModelRequest: {
            material: components["schemas"]["MaterialInput"];
            /** @default schematic */
            graph_view?: components["schemas"]["GraphView"];
        };
        /** MaterialModelResponse */
        MaterialModelResponse: {
            material: components["schemas"]["MaterialOut"];
            values: components["schemas"]["ModelValuesOut"];
            /** Hint */
            hint: string;
            /** Coefficients */
            coefficients: components["schemas"]["CoefficientsOut"][];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Figure
             * @description Plotly figure (data and layout)
             */
            figure: {
                [key: string]: unknown;
            };
        };
        /** MaterialOut */
        MaterialOut: {
            family: components["schemas"]["StainlessFamily"];
            /** Fy */
            fy: number;
            /** Fu */
            fu: number;
            /** Elastic Modulus */
            elastic_modulus: number;
            /** Source */
            source: string;
            /** Note */
            note: string | null;
        };
        /** ModelValuesOut */
        ModelValuesOut: {
            /** Yield Strain */
            yield_strain: number;
            /** Ultimate Strain */
            ultimate_strain: number;
            /** Strain Hardening Modulus */
            strain_hardening_modulus: number;
            /** Strain Limit C1 */
            strain_limit_c1: number;
            /** Strain End */
            strain_end: number;
            /** Stress At Strain Limit C1 */
            stress_at_strain_limit_c1: number;
            /** Hardening Ratio */
            hardening_ratio: number;
            /** Strain Limit Ratio C1 */
            strain_limit_ratio_c1: number;
        };
        /** PlateInput */
        PlateInput: {
            /** Label */
            label: string;
            /**
             * Width
             * @description Flat width b [mm]
             */
            width: number;
            /**
             * Thickness
             * @description Thickness t [mm]
             */
            thickness: number;
            /**
             * K Sigma
             * @description Buckling factor of the plate, an input
             */
            k_sigma: number;
        };
        /** PlateOut */
        PlateOut: {
            /** Label */
            label: string;
            /** Width */
            width: number;
            /** Thickness */
            thickness: number;
            /** Width To Thickness */
            width_to_thickness: number;
            /** K Sigma */
            k_sigma: number;
            /** Sigma Cr */
            sigma_cr: number;
            /** Slenderness */
            slenderness: number;
            /** Governing */
            governing: boolean;
        };
        /** ReferenceSectionOut */
        ReferenceSectionOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            point: components["schemas"]["ComparisonPointOut"];
        };
        /**
         * SectionType
         * @description Section families Annex B applies to (B.2).
         * @enum {string}
         */
        SectionType: "I-section" | "channel" | "T-section" | "angle" | "rectangular hollow section" | "circular hollow section";
        /**
         * SigmaCrSourceKey
         * @enum {string}
         */
        SigmaCrSourceKey: "plate_b9" | "chs_b11" | "user";
        /** SlendernessOut */
        SlendernessOut: {
            source: components["schemas"]["SigmaCrSourceKey"];
            /** Source Label */
            source_label: string;
            /** Sigma Cr Cs */
            sigma_cr_cs: number;
            /** Value */
            value: number;
            /** Governing Label */
            governing_label: string;
            /** Plates */
            plates: components["schemas"]["PlateOut"][];
        };
        /**
         * StainlessFamily
         * @enum {string}
         */
        StainlessFamily: "austenitic" | "duplex" | "ferritic";
        /** StrainLimitOut */
        StrainLimitOut: {
            zone: components["schemas"]["ZoneKey"];
            /** Allowed */
            allowed: boolean;
            /** Message */
            message: string | null;
            /** Cap */
            cap: number;
            cap_source: components["schemas"]["CapSourceKey"];
            /** Cap Label */
            cap_label: string;
            /** Raw Ratio */
            raw_ratio: number | null;
            /** Capped */
            capped: boolean;
            /** Strain Ratio */
            strain_ratio: number | null;
            /** Strain */
            strain: number | null;
            /** Switch */
            switch: number;
            /** Upper */
            upper: number;
        };
        /** SymbolOut */
        SymbolOut: {
            /** Symbol */
            symbol: string;
            /** Latex */
            latex: string;
            /** Name */
            name: string;
            /**
             * Meaning
             * @description One line explaining the symbol
             */
            meaning: string;
            /** Unit */
            unit: string;
            /** Clause */
            clause: string;
            /** Group */
            group: string;
            /** Topics */
            topics: string[];
            /**
             * Detail
             * @description The long explanation, for the Help page
             */
            detail: string;
            /**
             * Diagram
             * @description Name of the sketch drawn beside it
             */
            diagram?: string | null;
        };
        /** TensionInput */
        TensionInput: {
            /**
             * Area
             * @description Cross-section area A [mm2]
             */
            area: number;
            /** @description Only a label (B.2); no formula uses it */
            section_type?: components["schemas"]["SectionType"] | null;
            /**
             * Has Holes
             * @default false
             */
            has_holes?: boolean;
            /**
             * Gamma M0
             * @description Partial factor gamma_M0, an input
             */
            gamma_m0: number;
        };
        /** TensionRequest */
        TensionRequest: {
            material: components["schemas"]["MaterialInput"];
            tension: components["schemas"]["TensionInput"];
            /** @default schematic */
            graph_view?: components["schemas"]["GraphView"];
        };
        /** TensionResponse */
        TensionResponse: {
            material: components["schemas"]["MaterialOut"];
            /** Strain Ratio */
            strain_ratio: number;
            governing: components["schemas"]["GoverningKey"];
            /** Governing Label */
            governing_label: string;
            /** Strain */
            strain: number;
            /** Design Stress */
            design_stress: number;
            /**
             * Resistance
             * @description N_csm,t,Rd [N]
             */
            resistance: number;
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Figure
             * @description Plotly figure (data and layout)
             */
            figure: {
                [key: string]: unknown;
            };
        };
        /** TraceStepOut */
        TraceStepOut: {
            /** Symbol */
            symbol: string;
            /** Description */
            description: string;
            /** Clause */
            clause: string;
            /** Formula */
            formula: string;
            /** Substituted */
            substituted: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Line
             * @description The step as one readable line of working
             */
            line: string;
            /**
             * Latex
             * @description The step as one LaTeX equation (render with KaTeX)
             */
            latex: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ZoneKey
         * @enum {string}
         */
        ZoneKey: "stocky" | "slender" | "not_allowed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    grades_api_v1_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"][];
                };
            };
        };
    };
    symbols_api_v1_symbols_get: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    csm_coefficients_api_v1_csm_coefficients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoefficientsOut"][];
                };
            };
        };
    };
    material_model_api_v1_material_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    tension_api_v1_tension_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TensionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TensionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deformation_capacity_api_v1_deformation_capacity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeformationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeformationResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    section_comparison_api_v1_section_comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
