/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grades
         * @description Table 5.1.
         */
        get: operations["grades_api_v1_grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Symbols
         * @description The symbol glossary, one line per symbol. `topic` filters it (material, tension, ...).
         */
        get: operations["symbols_api_v1_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/input-help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Input Help
         * @description The "?" help for every input: what, why, where to get it, and its source tag.
         */
        get: operations["input_help_api_v1_input_help_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/csm-coefficients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csm Coefficients
         * @description Table B.1.
         */
        get: operations["csm_coefficients_api_v1_csm_coefficients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/material-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Material Model
         * @description B.4: the CSM bilinear model for a material.
         */
        post: operations["material_model_api_v1_material_model_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tension
         * @description B.6.1: CSM tension resistance.
         */
        post: operations["tension_api_v1_tension_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deformation-capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deformation Capacity
         * @description B.5: cross-section slenderness and the strain limit eps_csm / eps_y (B.6, B.7).
         */
        post: operations["deformation_capacity_api_v1_deformation_capacity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compression
         * @description B.6.2: CSM compression resistance (B.5 for the section, then B.15 to B.17).
         */
        post: operations["compression_api_v1_compression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bending
         * @description B.6.3.1(1) and B.6.3.2: CSM bending resistance about an axis of symmetry (B.5 for the
         *     section in bending, then B.19 or B.20 with the α of Table B.2).
         */
        post: operations["bending_api_v1_bending_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/section-properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Section Properties
         * @description A, centroid, I, W_el, W_pl, plastic axes and shear centre from the template dimensions.
         *
         *     Reference values (geometry, not a rule of EN 1993-1-4): they enter no calculation unless the
         *     user copies one into an input field.
         */
        post: operations["section_properties_api_v1_section_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/section-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Section Comparison
         * @description B.5 for the same section made thicker and thinner, to compare stocky with slender.
         */
        post: operations["section_comparison_api_v1_section_comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BendingAxisKey
         * @description The axis of bending (Table B.2): y-y is the major axis, z-z the minor axis.
         * @enum {string}
         */
        BendingAxisKey: "major" | "minor";
        /**
         * BendingFormulaKey
         * @description Which formula of B.6.3.2 gave the resistance (stable machine key).
         * @enum {string}
         */
        BendingFormulaKey: "b19" | "b20";
        /**
         * BendingParameterRowOut
         * @description One printed row of Table B.2.
         */
        BendingParameterRowOut: {
            /** Section */
            section: string;
            section_type: components["schemas"]["SectionType"];
            /**
             * Axis
             * @description major, minor or any
             */
            axis: string;
            /**
             * Aspect Ratio
             * @description As printed: Any, h/b < 2, -
             */
            aspect_ratio: string;
            /** Alpha */
            alpha: number;
            /**
             * Selected
             * @description The row that gave alpha for this section and axis
             */
            selected: boolean;
        };
        /**
         * BendingRequest
         * @description The section in bending (B.6.3.1(1), B.6.3.2): every value outside Annex B is an input.
         *
         *     In `geometry`, `k_sigma`, `plates[].k_sigma` and `sigma_cr_cs` are the values for the
         *     *bending* stress pattern about the chosen axis, not those of compression (EN 1993-1-5, 6.4.1).
         */
        BendingRequest: {
            material: components["schemas"]["MaterialInput"];
            section_type: components["schemas"]["SectionType"];
            /** @description Axis of bending; may be left out for a circular hollow section only */
            axis?: components["schemas"]["BendingAxisKey"] | null;
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input; not needed with sigma_cr
             */
            poisson_ratio?: number | null;
            /**
             * W El
             * @description Elastic section modulus W_el about the axis [mm3], an input
             */
            w_el: number;
            /**
             * W Pl
             * @description Plastic section modulus W_pl about the axis [mm3], an input
             */
            w_pl: number;
            /**
             * Gamma M0
             * @description Partial factor gamma_M0, an input
             */
            gamma_m0: number;
            /**
             * Lambda Lt
             * @description Relative slenderness for lateral-torsional buckling
             */
            lambda_lt: number;
        };
        /** BendingResponse */
        BendingResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            slenderness: components["schemas"]["SlendernessOut"];
            strain_limit: components["schemas"]["StrainLimitOut"];
            /**
             * Strain Ratio
             * @description eps_csm / eps_y, from B.5.1, section in bending
             */
            strain_ratio: number;
            formula: components["schemas"]["BendingFormulaKey"];
            /**
             * Formula Label
             * @description B.19 or B.20
             */
            formula_label: string;
            /**
             * Alpha
             * @description CSM bending parameter, Table B.2
             */
            alpha: number;
            /**
             * Table B2
             * @description Table B.2, the used row marked
             */
            table_b2: components["schemas"]["BendingParameterRowOut"][];
            /**
             * Elastic Moment
             * @description W_el f_y / gamma_M0 [N mm], a reference line
             */
            elastic_moment: number;
            /**
             * Plastic Moment
             * @description W_pl f_y / gamma_M0 [N mm], a reference line
             */
            plastic_moment: number;
            /**
             * Resistance
             * @description M_csm,c,Rd [N mm]
             */
            resistance: number;
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Moment Figure
             * @description Plotly figure: M_csm,c,Rd against eps_csm / eps_y
             */
            moment_figure: {
                [key: string]: unknown;
            };
            /**
             * Blocks Figure
             * @description Plotly figure: strain and stress across the depth at eps_csm
             */
            blocks_figure: {
                [key: string]: unknown;
            };
        };
        /**
         * CapSourceKey
         * @enum {string}
         */
        CapSourceKey: "omega" | "material_ductility";
        /** CoefficientsOut */
        CoefficientsOut: {
            family: components["schemas"]["StainlessFamily"];
            /** C1 */
            c1: number;
            /** C2 */
            c2: number;
            /** C3 */
            c3: number;
            /**
             * Selected
             * @default false
             */
            selected?: boolean;
        };
        /** ComparisonPointOut */
        ComparisonPointOut: {
            /**
             * Factor
             * @description Every thickness is multiplied by this
             */
            factor: number;
            /** Slenderness */
            slenderness: number;
            zone: components["schemas"]["ZoneKey"];
            /** Strain Ratio */
            strain_ratio: number | null;
            /** Strain */
            strain: number | null;
            /**
             * Stress
             * @description Stress read from the B.4 curve at the strain [N/mm2]
             */
            stress: number | null;
            /**
             * Governing Label
             * @description The plate that sets the slenderness at this point
             */
            governing_label: string;
        };
        /**
         * ComparisonRequest
         * @description Same inputs as B.5. The section must be plates or a circular hollow section.
         */
        ComparisonRequest: {
            material: components["schemas"]["MaterialInput"];
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input
             */
            poisson_ratio?: number | null;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            values: components["schemas"]["ModelValuesOut"];
            /** Switch */
            switch: number;
            /** Upper */
            upper: number;
            /** Cap */
            cap: number;
            /** Points */
            points: components["schemas"]["ComparisonPointOut"][];
            /** References */
            references: components["schemas"]["ReferenceSectionOut"][];
            /** Base Curve Figure */
            base_curve_figure: {
                [key: string]: unknown;
            };
            /** Stress Figure */
            stress_figure: {
                [key: string]: unknown;
            };
            /** Notes */
            notes: string[];
        };
        /**
         * CompressionFormulaKey
         * @description Which formula of B.6.2 gave the resistance (stable machine key).
         * @enum {string}
         */
        CompressionFormulaKey: "b15" | "b16";
        /**
         * CompressionRequest
         * @description The B.5 inputs of the section, plus the area and gamma_M0 (inputs, never assumed).
         */
        CompressionRequest: {
            material: components["schemas"]["MaterialInput"];
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input; not needed with sigma_cr
             */
            poisson_ratio?: number | null;
            /**
             * Area
             * @description Cross-section area A [mm2]
             */
            area: number;
            /**
             * Gamma M0
             * @description Partial factor gamma_M0, an input
             */
            gamma_m0: number;
            /** @default schematic */
            graph_view?: components["schemas"]["GraphView"];
        };
        /** CompressionResponse */
        CompressionResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            slenderness: components["schemas"]["SlendernessOut"];
            strain_limit: components["schemas"]["StrainLimitOut"];
            /**
             * Strain Ratio
             * @description eps_csm / eps_y, from B.5.1
             */
            strain_ratio: number;
            formula: components["schemas"]["CompressionFormulaKey"];
            /**
             * Formula Label
             * @description B.15 or B.16
             */
            formula_label: string;
            /**
             * Design Stress
             * @description f_csm [N/mm2] (Formula B.17); null when B.15 applies, where B.17 is not used
             */
            design_stress: number | null;
            /**
             * Resistance
             * @description N_csm,Rd [N]
             */
            resistance: number;
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Capacity Figure
             * @description Plotly figure: N_csm,Rd / (A f_y / gamma_M0) against slenderness
             */
            capacity_figure: {
                [key: string]: unknown;
            };
            /**
             * Point Figure
             * @description Plotly figure: the compression point on the B.4 curve
             */
            point_figure: {
                [key: string]: unknown;
            };
        };
        /** DeformationRequest */
        DeformationRequest: {
            material: components["schemas"]["MaterialInput"];
            geometry: components["schemas"]["GeometryInput"];
            /**
             * Omega
             * @description Parameter Omega, an input
             */
            omega: number;
            /**
             * Poisson Ratio
             * @description Poisson ratio nu, an input; not needed with sigma_cr
             */
            poisson_ratio?: number | null;
        };
        /** DeformationResponse */
        DeformationResponse: {
            material: components["schemas"]["MaterialOut"];
            family: components["schemas"]["FamilyKey"];
            slenderness: components["schemas"]["SlendernessOut"];
            strain_limit: components["schemas"]["StrainLimitOut"];
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /** Figure */
            figure: {
                [key: string]: unknown;
            };
        };
        /** ElasticModulusOut */
        ElasticModulusOut: {
            /**
             * Value
             * @description The smaller of the two [mm3]
             */
            value: number;
            /**
             * Smaller Side
             * @description Which fibre gives the smaller modulus; 'equal' when the two sides are equal
             */
            smaller_side: string;
            /**
             * Sides
             * @description The modulus at each extreme fibre [mm3]
             */
            sides: {
                [key: string]: number;
            };
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error Type */
            error_type: string;
        };
        /**
         * FabricationKey
         * @enum {string}
         */
        FabricationKey: "rolled" | "welded";
        /**
         * FamilyKey
         * @enum {string}
         */
        FamilyKey: "flat_plates" | "circular_hollow";
        /** FibreDistancesOut */
        FibreDistancesOut: {
            /** Top */
            top: number;
            /** Bottom */
            bottom: number;
            /** Left */
            left: number;
            /** Right */
            right: number;
        };
        /**
         * GeometryInput
         * @description The section. Which fields are needed depends on `kind` (the API says what is missing).
         *
         *     With kind "template" give `shape` and its dimensions in mm; the engine derives the flat width c
         *     of each plate as 8.2.2(5) and Tables 7.2 to 7.4 draw it. k_sigma of each plate is an input.
         */
        GeometryInput: {
            kind: components["schemas"]["GeometryKindKey"];
            /**
             * D
             * @description Outer diameter [mm] (CHS)
             */
            d?: number | null;
            /**
             * T
             * @description Wall thickness [mm] (CHS)
             */
            t?: number | null;
            /** Plates */
            plates?: components["schemas"]["PlateInput"][];
            /**
             * Sigma Cr Cs
             * @description sigma_cr,cs [N/mm2]
             */
            sigma_cr_cs?: number | null;
            /** @description With sigma_cr only */
            family?: components["schemas"]["FamilyKey"] | null;
            /** @description Section template: the shape */
            shape?: components["schemas"]["SectionType"] | null;
            /** @description Template I-section, channel, T-section: rolled (r) or welded (s) */
            fabrication?: components["schemas"]["FabricationKey"] | null;
            /**
             * H
             * @description Template: overall height h [mm]
             */
            h?: number | null;
            /**
             * B
             * @description Template: overall width b [mm]
             */
            b?: number | null;
            /**
             * T W
             * @description Template: web or stem thickness [mm]
             */
            t_w?: number | null;
            /**
             * T F
             * @description Template: flange thickness [mm]
             */
            t_f?: number | null;
            /**
             * R
             * @description Template: root radius r of a rolled section, or of an angle (properties and drawing only; 0 is sharp)
             */
            r?: number | null;
            /**
             * S
             * @description Template: weld leg s of a welded section
             */
            s?: number | null;
            /**
             * C Stem
             * @description Template T-section: flat width of the stem, typed [mm]
             */
            c_stem?: number | null;
            /**
             * R O
             * @description Template RHS: outer corner radius r_o [mm]; properties and drawing only, not c (0 is sharp)
             */
            r_o?: number | null;
            /** @description Template: k_sigma of each plate role */
            k_sigma?: components["schemas"]["KSigmaInput"] | null;
        };
        /**
         * GeometryKindKey
         * @enum {string}
         */
        GeometryKindKey: "chs" | "plates" | "sigma_cr" | "template";
        /**
         * GoverningKey
         * @description Which term of Formula B.14 governs the tensile strain limit (stable machine key).
         * @enum {string}
         */
        GoverningKey: "fixed_limit_15" | "material_ductility";
        /** GradeOut */
        GradeOut: {
            /** Designation */
            designation: string;
            /** Label */
            label: string;
            family: components["schemas"]["StainlessFamily"];
            /** Strength Class */
            strength_class: string | null;
            /** Corrosion Class */
            corrosion_class: string | null;
            /** Fy */
            fy: number;
            /** Fu */
            fu: number;
            /** Note */
            note: string | null;
        };
        /**
         * GraphView
         * @enum {string}
         */
        GraphView: "schematic" | "true_scale";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputHelpOut */
        InputHelpOut: {
            /**
             * Key
             * @description The dock field key (plate fields: one entry each)
             */
            key: string;
            /** Name */
            name: string;
            /**
             * What
             * @description What the input is
             */
            what: string;
            /**
             * Why
             * @description The clauses and formulas that use it
             */
            why: string;
            /**
             * Where
             * @description Where to get it; never a number of its own
             */
            where: string;
            /**
             * Source
             * @description 'In EN 1993-1-4 (clause)' or 'Outside EN 1993-1-4: ...'
             */
            source: string;
            /**
             * In Standard
             * @description True when the value comes from EN 1993-1-4
             */
            in_standard: boolean;
        };
        /**
         * KSigmaInput
         * @description k_sigma of each kind of plate (EN 1993-1-5, outside Annex B): an input, one per role.
         */
        KSigmaInput: {
            /** Web */
            web?: number | null;
            /** Flange */
            flange?: number | null;
            /** Stem */
            stem?: number | null;
            /** Leg */
            leg?: number | null;
        };
        /**
         * MaterialInput
         * @description A Table 5.1 grade (give `designation`) or a custom material (leave it out).
         */
        MaterialInput: {
            /**
             * Designation
             * @example 1.4307
             */
            designation?: string | null;
            family?: components["schemas"]["StainlessFamily"] | null;
            /**
             * Fy
             * @description Yield strength [N/mm2], custom only
             */
            fy?: number | null;
            /**
             * Fu
             * @description Ultimate strength [N/mm2], custom only
             */
            fu?: number | null;
            /**
             * Elastic Modulus
             * @description E [N/mm2], an input
             */
            elastic_modulus: number;
            /**
             * Enhanced
             * @description Custom values enhanced by cold-forming
             * @default false
             */
            enhanced?: boolean;
        };
        /** MaterialModelRequest */
        MaterialModelRequest: {
            material: components["schemas"]["MaterialInput"];
            /** @default schematic */
            graph_view?: components["schemas"]["GraphView"];
        };
        /** MaterialModelResponse */
        MaterialModelResponse: {
            material: components["schemas"]["MaterialOut"];
            values: components["schemas"]["ModelValuesOut"];
            /** Hint */
            hint: string;
            /** Coefficients */
            coefficients: components["schemas"]["CoefficientsOut"][];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Figure
             * @description Plotly figure (data and layout)
             */
            figure: {
                [key: string]: unknown;
            };
        };
        /** MaterialOut */
        MaterialOut: {
            family: components["schemas"]["StainlessFamily"];
            /** Fy */
            fy: number;
            /** Fu */
            fu: number;
            /** Elastic Modulus */
            elastic_modulus: number;
            /** Source */
            source: string;
            /** Note */
            note: string | null;
        };
        /** ModelValuesOut */
        ModelValuesOut: {
            /** Yield Strain */
            yield_strain: number;
            /** Ultimate Strain */
            ultimate_strain: number;
            /** Strain Hardening Modulus */
            strain_hardening_modulus: number;
            /** Strain Limit C1 */
            strain_limit_c1: number;
            /** Strain End */
            strain_end: number;
            /** Stress At Strain Limit C1 */
            stress_at_strain_limit_c1: number;
            /** Hardening Ratio */
            hardening_ratio: number;
            /** Strain Limit Ratio C1 */
            strain_limit_ratio_c1: number;
        };
        /** PlateInput */
        PlateInput: {
            /** Label */
            label: string;
            /**
             * Width
             * @description Flat width b [mm]
             */
            width: number;
            /**
             * Thickness
             * @description Thickness t [mm]
             */
            thickness: number;
            /**
             * K Sigma
             * @description Buckling factor of the plate, an input
             */
            k_sigma: number;
        };
        /** PlateOut */
        PlateOut: {
            /** Label */
            label: string;
            /** Width */
            width: number;
            /** Thickness */
            thickness: number;
            /** Width To Thickness */
            width_to_thickness: number;
            /** K Sigma */
            k_sigma: number;
            /** Sigma Cr */
            sigma_cr: number;
            /** Slenderness */
            slenderness: number;
            /** Governing */
            governing: boolean;
            /** @description Section template only: which part of the section this is */
            role?: components["schemas"]["PlateRoleKey"] | null;
            /** @description Section template only: internal or outstand */
            plate_type?: components["schemas"]["PlateTypeKey"] | null;
            /**
             * C Source
             * @description Section template only: where the flat width c comes from
             */
            c_source?: string | null;
        };
        /**
         * PlateRoleKey
         * @enum {string}
         */
        PlateRoleKey: "web" | "flange" | "stem" | "leg";
        /**
         * PlateTypeKey
         * @enum {string}
         */
        PlateTypeKey: "internal" | "outstand";
        /** PointOut */
        PointOut: {
            /**
             * Y
             * @description mm, from the origin to the right
             */
            y: number;
            /**
             * Z
             * @description mm, from the origin upwards
             */
            z: number;
        };
        /** PrincipalAxesOut */
        PrincipalAxesOut: {
            /**
             * Angle Deg
             * @description Angle of the major axis u from the y axis, counter-clockwise, z up [degrees]
             */
            angle_deg: number;
            /** I U */
            i_u: number;
            /** I V */
            i_v: number;
        };
        /**
         * PropertyRowOut
         * @description One line of the properties table. `value` has six significant figures (what Use copies).
         */
        PropertyRowOut: {
            /**
             * Key
             * @description A stable machine key, for example A, I_y, W_pl_y
             */
            key: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Group */
            group: string;
            /** Note */
            note?: string | null;
        };
        /** ReferenceSectionOut */
        ReferenceSectionOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            point: components["schemas"]["ComparisonPointOut"];
        };
        /**
         * SectionPropertiesRequest
         * @description The typed template dimensions in mm. Which ones are needed depends on `shape`.
         */
        SectionPropertiesRequest: {
            shape: components["schemas"]["SectionType"];
            /** @description I-section, channel and T-section: rolled (r) or welded (s) */
            fabrication?: components["schemas"]["FabricationKey"] | null;
            /**
             * H
             * @description Overall height h [mm] (longer leg: angle)
             */
            h?: number | null;
            /**
             * B
             * @description Overall width b [mm] (shorter leg: angle)
             */
            b?: number | null;
            /**
             * T W
             * @description Web or stem thickness [mm]
             */
            t_w?: number | null;
            /**
             * T F
             * @description Flange thickness [mm]
             */
            t_f?: number | null;
            /**
             * T
             * @description Wall or leg thickness [mm]
             */
            t?: number | null;
            /**
             * D
             * @description Outer diameter [mm] (CHS)
             */
            d?: number | null;
            /**
             * R
             * @description Root radius r [mm]: rolled I, channel, T-section, or an angle
             */
            r?: number | null;
            /**
             * S
             * @description Weld leg s [mm]: welded sections
             */
            s?: number | null;
            /**
             * R O
             * @description Outer corner radius r_o [mm] of a rectangular hollow section
             */
            r_o?: number | null;
        };
        /** SectionPropertiesResponse */
        SectionPropertiesResponse: {
            shape: components["schemas"]["SectionType"];
            /**
             * Label
             * @description Where these numbers come from: geometry, not the standard
             */
            label: string;
            /** Method */
            method: string;
            /**
             * Origin
             * @description Where the coordinates start
             */
            origin: string;
            /**
             * Width
             * @description Bounding box along y [mm]
             */
            width: number;
            /**
             * Height
             * @description Bounding box along z [mm]
             */
            height: number;
            /**
             * Area
             * @description A [mm2]
             */
            area: number;
            centroid: components["schemas"]["PointOut"];
            /** @description Centroid to the extreme fibres [mm] */
            fibres: components["schemas"]["FibreDistancesOut"];
            /**
             * I Y
             * @description [mm4], about the centroidal axis parallel to y
             */
            i_y: number;
            /** I Z */
            i_z: number;
            /** I Yz */
            i_yz: number;
            w_el_y: components["schemas"]["ElasticModulusOut"];
            w_el_z: components["schemas"]["ElasticModulusOut"];
            /**
             * Plastic Axis Y
             * @description z of the equal-area line parallel to y, for bending about y-y [mm]
             */
            plastic_axis_y: number;
            /**
             * Plastic Axis Z
             * @description y of the equal-area line parallel to z, for bending about z-z [mm]
             */
            plastic_axis_z: number;
            /**
             * W Pl Y
             * @description [mm3]
             */
            w_pl_y: number;
            /** W Pl Z */
            w_pl_z: number;
            shear_centre: components["schemas"]["ShearCentreOut"];
            /** @description Angles only */
            principal?: components["schemas"]["PrincipalAxesOut"] | null;
            /** Rows */
            rows: components["schemas"]["PropertyRowOut"][];
            /** Notes */
            notes: string[];
        };
        /**
         * SectionType
         * @description Section families Annex B applies to (B.2).
         * @enum {string}
         */
        SectionType: "I-section" | "channel" | "T-section" | "angle" | "rectangular hollow section" | "circular hollow section";
        /** ShearCentreOut */
        ShearCentreOut: {
            point: components["schemas"]["PointOut"];
            /**
             * Label
             * @description Always 'thin-walled approximation'
             */
            label: string;
            /** Note */
            note: string;
        };
        /**
         * SigmaCrSourceKey
         * @enum {string}
         */
        SigmaCrSourceKey: "plate_b9" | "chs_b11" | "user";
        /** SlendernessOut */
        SlendernessOut: {
            source: components["schemas"]["SigmaCrSourceKey"];
            /** Source Label */
            source_label: string;
            /** Sigma Cr Cs */
            sigma_cr_cs: number;
            /** Value */
            value: number;
            /** Governing Label */
            governing_label: string;
            /** Plates */
            plates: components["schemas"]["PlateOut"][];
        };
        /**
         * StainlessFamily
         * @enum {string}
         */
        StainlessFamily: "austenitic" | "duplex" | "ferritic";
        /** StrainLimitOut */
        StrainLimitOut: {
            zone: components["schemas"]["ZoneKey"];
            /** Allowed */
            allowed: boolean;
            /** Message */
            message: string | null;
            /** Cap */
            cap: number;
            cap_source: components["schemas"]["CapSourceKey"];
            /** Cap Label */
            cap_label: string;
            /** Raw Ratio */
            raw_ratio: number | null;
            /** Capped */
            capped: boolean;
            /** Strain Ratio */
            strain_ratio: number | null;
            /** Strain */
            strain: number | null;
            /** Switch */
            switch: number;
            /** Upper */
            upper: number;
        };
        /** SymbolOut */
        SymbolOut: {
            /** Symbol */
            symbol: string;
            /** Latex */
            latex: string;
            /** Name */
            name: string;
            /**
             * Meaning
             * @description One line explaining the symbol
             */
            meaning: string;
            /** Unit */
            unit: string;
            /** Clause */
            clause: string;
            /** Group */
            group: string;
            /** Topics */
            topics: string[];
            /**
             * Detail
             * @description The long explanation, for the Help page
             */
            detail: string;
            /**
             * Diagram
             * @description Name of the sketch drawn beside it
             */
            diagram?: string | null;
        };
        /** TensionInput */
        TensionInput: {
            /**
             * Area
             * @description Cross-section area A [mm2]
             */
            area: number;
            /** @description Only a label (B.2); no formula uses it */
            section_type?: components["schemas"]["SectionType"] | null;
            /**
             * Has Holes
             * @default false
             */
            has_holes?: boolean;
            /**
             * Gamma M0
             * @description Partial factor gamma_M0, an input
             */
            gamma_m0: number;
        };
        /** TensionRequest */
        TensionRequest: {
            material: components["schemas"]["MaterialInput"];
            tension: components["schemas"]["TensionInput"];
            /** @default schematic */
            graph_view?: components["schemas"]["GraphView"];
        };
        /** TensionResponse */
        TensionResponse: {
            material: components["schemas"]["MaterialOut"];
            /** Strain Ratio */
            strain_ratio: number;
            governing: components["schemas"]["GoverningKey"];
            /** Governing Label */
            governing_label: string;
            /** Strain */
            strain: number;
            /** Design Stress */
            design_stress: number;
            /**
             * Resistance
             * @description N_csm,t,Rd [N]
             */
            resistance: number;
            /** Notes */
            notes: string[];
            /** Trace */
            trace: components["schemas"]["TraceStepOut"][];
            /**
             * Figure
             * @description Plotly figure (data and layout)
             */
            figure: {
                [key: string]: unknown;
            };
        };
        /** TraceStepOut */
        TraceStepOut: {
            /** Symbol */
            symbol: string;
            /** Description */
            description: string;
            /** Clause */
            clause: string;
            /** Formula */
            formula: string;
            /** Substituted */
            substituted: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Line
             * @description The step as one readable line of working
             */
            line: string;
            /**
             * Latex
             * @description The step as one LaTeX equation (render with KaTeX)
             */
            latex: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ZoneKey
         * @enum {string}
         */
        ZoneKey: "stocky" | "slender" | "not_allowed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    grades_api_v1_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"][];
                };
            };
        };
    };
    symbols_api_v1_symbols_get: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    input_help_api_v1_input_help_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputHelpOut"][];
                };
            };
        };
    };
    csm_coefficients_api_v1_csm_coefficients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoefficientsOut"][];
                };
            };
        };
    };
    material_model_api_v1_material_model_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialModelResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    tension_api_v1_tension_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TensionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TensionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deformation_capacity_api_v1_deformation_capacity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeformationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeformationResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compression_api_v1_compression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompressionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bending_api_v1_bending_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BendingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BendingResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    section_properties_api_v1_section_properties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionPropertiesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionPropertiesResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    section_comparison_api_v1_section_comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
